services:
  react-weaver.db:
    image: postgres:18.1
    container_name: react-weaver.db
    restart: always
    user: postgres
    volumes:
      - react-weaver.db-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  react-weaver.garage:
    image: dxflrs/garage:v2.3.0
    container_name: react-weaver.garage
    restart: unless-stopped
    ports:
      - "3900:3900"
      - "3903:3903"
    environment:
      GARAGE_DEFAULT_BUCKET: uploads
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
      - ./garage/data:/var/lib/garage/data
      - ./garage/meta:/var/lib/garage/meta

volumes:
  react-weaver.db-data:
