// This file is auto-generated by @hey-api/openapi-ts

export const CreateWeatherForecastRequestSchema = {
    required: [
        'date',
        'temperatureC'
    ],
    type: 'object',
    properties: {
        date: {
            type: 'string',
            format: 'date'
        },
        temperatureC: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        summary: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const ForgotPasswordRequestSchema = {
    required: [
        'email'
    ],
    type: 'object',
    properties: {
        email: {
            type: 'string'
        }
    }
} as const;

export const LoginRequestSchema = {
    required: [
        'email',
        'password'
    ],
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        twoFactorCode: {
            type: [
                'null',
                'string'
            ]
        },
        twoFactorRecoveryCode: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const ProblemDetailsSchema = {
    type: 'object',
    properties: {
        type: {
            type: [
                'null',
                'string'
            ]
        },
        title: {
            type: [
                'null',
                'string'
            ]
        },
        status: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'null',
                'integer',
                'string'
            ],
            format: 'int32'
        },
        detail: {
            type: [
                'null',
                'string'
            ]
        },
        instance: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const RegisterRequestSchema = {
    required: [
        'email',
        'password'
    ],
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const RemoveWeatherForecastsRequestSchema = {
    required: [
        'ids'
    ],
    type: 'object',
    properties: {
        ids: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const ResendConfirmationEmailRequestSchema = {
    required: [
        'email'
    ],
    type: 'object',
    properties: {
        email: {
            type: 'string'
        }
    }
} as const;

export const ResetPasswordRequestSchema = {
    required: [
        'email',
        'resetCode',
        'newPassword'
    ],
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        resetCode: {
            type: 'string'
        },
        newPassword: {
            type: 'string'
        }
    }
} as const;

export const UpdateUserInfoRequestSchema = {
    required: [
        'newEmail',
        'newPassword',
        'oldPassword'
    ],
    type: 'object',
    properties: {
        newEmail: {
            type: 'string'
        },
        newPassword: {
            type: 'string'
        },
        oldPassword: {
            type: 'string'
        }
    }
} as const;

export const UpdateWeatherForecastRequestSchema = {
    required: [
        'date',
        'temperatureC'
    ],
    type: 'object',
    properties: {
        date: {
            type: 'string',
            format: 'date'
        },
        temperatureC: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        summary: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;

export const UserResponseSchema = {
    required: [
        'id',
        'email',
        'roles',
        'isEmailConfirmed'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        isEmailConfirmed: {
            type: 'boolean'
        }
    }
} as const;

export const WeatherForecastResponseSchema = {
    required: [
        'id',
        'date',
        'temperatureC',
        'summary'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        date: {
            type: 'string',
            format: 'date'
        },
        temperatureC: {
            pattern: '^-?(?:0|[1-9]\\d*)$',
            type: [
                'integer',
                'string'
            ],
            format: 'int32'
        },
        summary: {
            type: [
                'null',
                'string'
            ]
        }
    }
} as const;
