// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ConfirmEmailData, ConfirmEmailErrors, CreateWeatherForecastData, CreateWeatherForecastErrors, CreateWeatherForecastResponses, ForgotPasswordData, ForgotPasswordErrors, ForgotPasswordResponses, GetCurrentUserData, GetCurrentUserResponses, GetUsersData, GetUsersResponses, GetWeatherForecastData, GetWeatherForecastErrors, GetWeatherForecastResponses, GetWeatherForecastsData, GetWeatherForecastsErrors, GetWeatherForecastsResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, RegisterData, RegisterErrors, RegisterResponses, RemoveUserData, RemoveUserErrors, RemoveUserResponses, RemoveUsersData, RemoveUsersResponses, RemoveWeatherForecastData, RemoveWeatherForecastErrors, RemoveWeatherForecastResponses, RemoveWeatherForecastsData, RemoveWeatherForecastsErrors, RemoveWeatherForecastsResponses, ResendConfirmationEmailData, ResendConfirmationEmailErrors, ResendConfirmationEmailResponses, ResetPasswordData, ResetPasswordErrors, ResetPasswordResponses, UpdateInfoData, UpdateInfoErrors, UpdateInfoResponses, UpdateWeatherForecastData, UpdateWeatherForecastErrors, UpdateWeatherForecastResponses } from './types.gen';
import { zConfirmEmailQuery, zCreateWeatherForecastBody, zCreateWeatherForecastResponse, zForgotPasswordBody, zGetCurrentUserResponse, zGetUsersResponse, zGetWeatherForecastPath, zGetWeatherForecastResponse, zGetWeatherForecastsResponse, zLoginBody, zLoginQuery, zLoginResponse, zRegisterBody, zRemoveUserPath, zRemoveUserResponse, zRemoveUsersBody, zRemoveUsersResponse, zRemoveWeatherForecastPath, zRemoveWeatherForecastResponse, zRemoveWeatherForecastsBody, zRemoveWeatherForecastsResponse, zResendConfirmationEmailBody, zResetPasswordBody, zUpdateInfoBody, zUpdateInfoResponse, zUpdateWeatherForecastBody, zUpdateWeatherForecastPath, zUpdateWeatherForecastResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getWeatherForecasts = <ThrowOnError extends boolean = false>(options?: Options<GetWeatherForecastsData, ThrowOnError>): RequestResult<GetWeatherForecastsResponses, GetWeatherForecastsErrors, ThrowOnError> => (options?.client ?? client).get<GetWeatherForecastsResponses, GetWeatherForecastsErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetWeatherForecastsResponse.parseAsync(data),
    url: '/api/weather-forecasts',
    ...options
});

export const createWeatherForecast = <ThrowOnError extends boolean = false>(options: Options<CreateWeatherForecastData, ThrowOnError>): RequestResult<CreateWeatherForecastResponses, CreateWeatherForecastErrors, ThrowOnError> => (options.client ?? client).post<CreateWeatherForecastResponses, CreateWeatherForecastErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateWeatherForecastBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateWeatherForecastResponse.parseAsync(data),
    url: '/api/weather-forecasts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const removeWeatherForecast = <ThrowOnError extends boolean = false>(options: Options<RemoveWeatherForecastData, ThrowOnError>): RequestResult<RemoveWeatherForecastResponses, RemoveWeatherForecastErrors, ThrowOnError> => (options.client ?? client).delete<RemoveWeatherForecastResponses, RemoveWeatherForecastErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zRemoveWeatherForecastPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zRemoveWeatherForecastResponse.parseAsync(data),
    url: '/api/weather-forecasts/{id}',
    ...options
});

export const getWeatherForecast = <ThrowOnError extends boolean = false>(options: Options<GetWeatherForecastData, ThrowOnError>): RequestResult<GetWeatherForecastResponses, GetWeatherForecastErrors, ThrowOnError> => (options.client ?? client).get<GetWeatherForecastResponses, GetWeatherForecastErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zGetWeatherForecastPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetWeatherForecastResponse.parseAsync(data),
    url: '/api/weather-forecasts/{id}',
    ...options
});

export const updateWeatherForecast = <ThrowOnError extends boolean = false>(options: Options<UpdateWeatherForecastData, ThrowOnError>): RequestResult<UpdateWeatherForecastResponses, UpdateWeatherForecastErrors, ThrowOnError> => (options.client ?? client).put<UpdateWeatherForecastResponses, UpdateWeatherForecastErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUpdateWeatherForecastBody,
        path: zUpdateWeatherForecastPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zUpdateWeatherForecastResponse.parseAsync(data),
    url: '/api/weather-forecasts/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const removeWeatherForecasts = <ThrowOnError extends boolean = false>(options: Options<RemoveWeatherForecastsData, ThrowOnError>): RequestResult<RemoveWeatherForecastsResponses, RemoveWeatherForecastsErrors, ThrowOnError> => (options.client ?? client).post<RemoveWeatherForecastsResponses, RemoveWeatherForecastsErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zRemoveWeatherForecastsBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zRemoveWeatherForecastsResponse.parseAsync(data),
    url: '/api/weather-forecasts/bulk-delete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetCurrentUserResponse.parseAsync(data),
    url: '/api/users/me',
    ...options
});

export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>): RequestResult<GetUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetUsersResponse.parseAsync(data),
    url: '/api/users',
    ...options
});

export const removeUser = <ThrowOnError extends boolean = false>(options: Options<RemoveUserData, ThrowOnError>): RequestResult<RemoveUserResponses, RemoveUserErrors, ThrowOnError> => (options.client ?? client).delete<RemoveUserResponses, RemoveUserErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zRemoveUserPath,
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zRemoveUserResponse.parseAsync(data),
    url: '/api/users/{id}',
    ...options
});

export const removeUsers = <ThrowOnError extends boolean = false>(options: Options<RemoveUsersData, ThrowOnError>): RequestResult<RemoveUsersResponses, unknown, ThrowOnError> => (options.client ?? client).post<RemoveUsersResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zRemoveUsersBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zRemoveUsersResponse.parseAsync(data),
    url: '/api/users/bulk-delete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zRegisterBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zLoginBody,
        path: z.never().optional(),
        query: zLoginQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zLoginResponse.parseAsync(data),
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/auth/logout',
    ...options
});

export const confirmEmail = <ThrowOnError extends boolean = false>(options?: Options<ConfirmEmailData, ThrowOnError>): RequestResult<unknown, ConfirmEmailErrors, ThrowOnError> => (options?.client ?? client).get<unknown, ConfirmEmailErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: zConfirmEmailQuery.optional()
    }).parseAsync(data),
    url: '/api/auth/confirmEmail',
    ...options
});

export const resendConfirmationEmail = <ThrowOnError extends boolean = false>(options: Options<ResendConfirmationEmailData, ThrowOnError>): RequestResult<ResendConfirmationEmailResponses, ResendConfirmationEmailErrors, ThrowOnError> => (options.client ?? client).post<ResendConfirmationEmailResponses, ResendConfirmationEmailErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zResendConfirmationEmailBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/auth/resendConfirmationEmail',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const forgotPassword = <ThrowOnError extends boolean = false>(options: Options<ForgotPasswordData, ThrowOnError>): RequestResult<ForgotPasswordResponses, ForgotPasswordErrors, ThrowOnError> => (options.client ?? client).post<ForgotPasswordResponses, ForgotPasswordErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zForgotPasswordBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/auth/forgotPassword',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const resetPassword = <ThrowOnError extends boolean = false>(options: Options<ResetPasswordData, ThrowOnError>): RequestResult<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError> => (options.client ?? client).post<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zResetPasswordBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/auth/resetPassword',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const updateInfo = <ThrowOnError extends boolean = false>(options: Options<UpdateInfoData, ThrowOnError>): RequestResult<UpdateInfoResponses, UpdateInfoErrors, ThrowOnError> => (options.client ?? client).post<UpdateInfoResponses, UpdateInfoErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUpdateInfoBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zUpdateInfoResponse.parseAsync(data),
    url: '/api/auth/info',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
