// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CreateWeatherForecastRequest = {
    date: string;
    temperatureC: number | string;
    summary?: null | string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type LoginRequest = {
    email: string;
    password: string;
    twoFactorCode?: null | string;
    twoFactorRecoveryCode?: null | string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type RemoveWeatherForecastsRequest = {
    ids: Array<string>;
};

export type ResendConfirmationEmailRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    email: string;
    resetCode: string;
    newPassword: string;
};

export type UpdateUserInfoRequest = {
    newEmail: string;
    newPassword: string;
    oldPassword: string;
};

export type UpdateWeatherForecastRequest = {
    date: string;
    temperatureC: number | string;
    summary?: null | string;
};

export type UserResponse = {
    id: string;
    email: string;
    roles: Array<string>;
    isEmailConfirmed: boolean;
};

export type WeatherForecastResponse = {
    id: string;
    date: string;
    temperatureC: number | string;
    summary: null | string;
};

export type GetWeatherForecastsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/weather-forecasts';
};

export type GetWeatherForecastsErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetWeatherForecastsError = GetWeatherForecastsErrors[keyof GetWeatherForecastsErrors];

export type GetWeatherForecastsResponses = {
    /**
     * OK
     */
    200: Array<WeatherForecastResponse>;
};

export type GetWeatherForecastsResponse = GetWeatherForecastsResponses[keyof GetWeatherForecastsResponses];

export type CreateWeatherForecastData = {
    body: CreateWeatherForecastRequest;
    path?: never;
    query?: never;
    url: '/api/weather-forecasts';
};

export type CreateWeatherForecastErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type CreateWeatherForecastError = CreateWeatherForecastErrors[keyof CreateWeatherForecastErrors];

export type CreateWeatherForecastResponses = {
    /**
     * Created
     */
    201: WeatherForecastResponse;
};

export type CreateWeatherForecastResponse = CreateWeatherForecastResponses[keyof CreateWeatherForecastResponses];

export type RemoveWeatherForecastData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/weather-forecasts/{id}';
};

export type RemoveWeatherForecastErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type RemoveWeatherForecastError = RemoveWeatherForecastErrors[keyof RemoveWeatherForecastErrors];

export type RemoveWeatherForecastResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveWeatherForecastResponse = RemoveWeatherForecastResponses[keyof RemoveWeatherForecastResponses];

export type GetWeatherForecastData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/weather-forecasts/{id}';
};

export type GetWeatherForecastErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetWeatherForecastError = GetWeatherForecastErrors[keyof GetWeatherForecastErrors];

export type GetWeatherForecastResponses = {
    /**
     * OK
     */
    200: WeatherForecastResponse;
};

export type GetWeatherForecastResponse = GetWeatherForecastResponses[keyof GetWeatherForecastResponses];

export type UpdateWeatherForecastData = {
    body: UpdateWeatherForecastRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/weather-forecasts/{id}';
};

export type UpdateWeatherForecastErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type UpdateWeatherForecastError = UpdateWeatherForecastErrors[keyof UpdateWeatherForecastErrors];

export type UpdateWeatherForecastResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateWeatherForecastResponse = UpdateWeatherForecastResponses[keyof UpdateWeatherForecastResponses];

export type RemoveWeatherForecastsData = {
    body: RemoveWeatherForecastsRequest;
    path?: never;
    query?: never;
    url: '/api/weather-forecasts/bulk-delete';
};

export type RemoveWeatherForecastsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type RemoveWeatherForecastsError = RemoveWeatherForecastsErrors[keyof RemoveWeatherForecastsErrors];

export type RemoveWeatherForecastsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveWeatherForecastsResponse = RemoveWeatherForecastsResponses[keyof RemoveWeatherForecastsResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: Array<UserResponse>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type RemoveUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type RemoveUserErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type RemoveUserError = RemoveUserErrors[keyof RemoveUserErrors];

export type RemoveUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveUserResponse = RemoveUserResponses[keyof RemoveUserResponses];

export type RemoveUsersData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/api/users/bulk-delete';
};

export type RemoveUsersResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveUsersResponse = RemoveUsersResponses[keyof RemoveUsersResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ConfirmEmailData = {
    body?: never;
    path?: never;
    query?: {
        userId?: string;
        code?: string;
        changedEmail?: string;
    };
    url: '/api/auth/confirmEmail';
};

export type ConfirmEmailErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type ConfirmEmailError = ConfirmEmailErrors[keyof ConfirmEmailErrors];

export type ResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/api/auth/resendConfirmationEmail';
};

export type ResendConfirmationEmailErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type ResendConfirmationEmailError = ResendConfirmationEmailErrors[keyof ResendConfirmationEmailErrors];

export type ResendConfirmationEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/forgotPassword';
};

export type ForgotPasswordErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type ForgotPasswordError = ForgotPasswordErrors[keyof ForgotPasswordErrors];

export type ForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/resetPassword';
};

export type ResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateInfoData = {
    body: UpdateUserInfoRequest;
    path?: never;
    query?: never;
    url: '/api/auth/info';
};

export type UpdateInfoErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type UpdateInfoError = UpdateInfoErrors[keyof UpdateInfoErrors];

export type UpdateInfoResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type UpdateInfoResponse = UpdateInfoResponses[keyof UpdateInfoResponses];
