// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zCreateWeatherForecastRequest = z.object({
    date: z.iso.date(),
    temperatureC: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]),
    summary: z.string().nullish()
});

export const zForgotPasswordRequest = z.object({
    email: z.string()
});

export const zLoginRequest = z.object({
    email: z.string(),
    password: z.string(),
    twoFactorCode: z.string().nullish(),
    twoFactorRecoveryCode: z.string().nullish()
});

export const zProblemDetails = z.object({
    type: z.string().nullish(),
    title: z.string().nullish(),
    status: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]).nullish(),
    detail: z.string().nullish(),
    instance: z.string().nullish()
});

export const zRegisterRequest = z.object({
    email: z.string(),
    password: z.string()
});

export const zRemoveWeatherForecastsRequest = z.object({
    ids: z.array(z.string())
});

export const zResendConfirmationEmailRequest = z.object({
    email: z.string()
});

export const zResetPasswordRequest = z.object({
    email: z.string(),
    resetCode: z.string(),
    newPassword: z.string()
});

export const zUpdateUserInfoRequest = z.object({
    newEmail: z.string(),
    newPassword: z.string(),
    oldPassword: z.string()
});

export const zUpdateWeatherForecastRequest = z.object({
    date: z.iso.date(),
    temperatureC: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]),
    summary: z.string().nullish()
});

export const zUserResponse = z.object({
    id: z.string(),
    email: z.string(),
    roles: z.array(z.string()),
    isEmailConfirmed: z.boolean()
});

export const zWeatherForecastResponse = z.object({
    id: z.string(),
    date: z.iso.date(),
    temperatureC: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]),
    summary: z.string().nullable()
});

/**
 * OK
 */
export const zGetWeatherForecastsResponse = z.array(zWeatherForecastResponse);

export const zCreateWeatherForecastBody = zCreateWeatherForecastRequest;

/**
 * Created
 */
export const zCreateWeatherForecastResponse = zWeatherForecastResponse;

export const zRemoveWeatherForecastPath = z.object({
    id: z.string()
});

/**
 * No Content
 */
export const zRemoveWeatherForecastResponse = z.void();

export const zGetWeatherForecastPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetWeatherForecastResponse = zWeatherForecastResponse;

export const zUpdateWeatherForecastBody = zUpdateWeatherForecastRequest;

export const zUpdateWeatherForecastPath = z.object({
    id: z.string()
});

/**
 * No Content
 */
export const zUpdateWeatherForecastResponse = z.void();

export const zRemoveWeatherForecastsBody = zRemoveWeatherForecastsRequest;

/**
 * No Content
 */
export const zRemoveWeatherForecastsResponse = z.void();

/**
 * OK
 */
export const zGetCurrentUserResponse = zUserResponse;

/**
 * OK
 */
export const zGetUsersResponse = z.array(zUserResponse);

export const zRemoveUserPath = z.object({
    id: z.string()
});

/**
 * No Content
 */
export const zRemoveUserResponse = z.void();

export const zRemoveUsersBody = z.array(z.string());

/**
 * No Content
 */
export const zRemoveUsersResponse = z.void();

export const zRegisterBody = zRegisterRequest;

export const zLoginBody = zLoginRequest;

export const zLoginQuery = z.object({
    useCookies: z.boolean().optional(),
    useSessionCookies: z.boolean().optional()
});

/**
 * No Content
 */
export const zLoginResponse = z.void();

export const zConfirmEmailQuery = z.object({
    userId: z.string().optional(),
    code: z.string().optional(),
    changedEmail: z.string().optional()
});

export const zResendConfirmationEmailBody = zResendConfirmationEmailRequest;

export const zForgotPasswordBody = zForgotPasswordRequest;

export const zResetPasswordBody = zResetPasswordRequest;

export const zUpdateInfoBody = zUpdateUserInfoRequest;

/**
 * OK
 */
export const zUpdateInfoResponse = zUserResponse;
