// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { confirmEmail, createWeatherForecast, forgotPassword, getCurrentUser, getUsers, getWeatherForecast, getWeatherForecasts, login, logout, type Options, register, removeUser, removeUsers, removeWeatherForecast, removeWeatherForecasts, resendConfirmationEmail, resetPassword, updateInfo, updateWeatherForecast } from '../sdk.gen';
import type { ConfirmEmailData, ConfirmEmailError, CreateWeatherForecastData, CreateWeatherForecastError, CreateWeatherForecastResponse, ForgotPasswordData, ForgotPasswordError, GetCurrentUserData, GetCurrentUserResponse, GetUsersData, GetUsersResponse, GetWeatherForecastData, GetWeatherForecastError, GetWeatherForecastResponse, GetWeatherForecastsData, GetWeatherForecastsError, GetWeatherForecastsResponse, LoginData, LoginError, LoginResponse, LogoutData, LogoutError, RegisterData, RegisterError, RemoveUserData, RemoveUserError, RemoveUserResponse, RemoveUsersData, RemoveUsersResponse, RemoveWeatherForecastData, RemoveWeatherForecastError, RemoveWeatherForecastResponse, RemoveWeatherForecastsData, RemoveWeatherForecastsError, RemoveWeatherForecastsResponse, ResendConfirmationEmailData, ResendConfirmationEmailError, ResetPasswordData, ResetPasswordError, UpdateInfoData, UpdateInfoError, UpdateInfoResponse, UpdateWeatherForecastData, UpdateWeatherForecastError, UpdateWeatherForecastResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getWeatherForecastsQueryKey = (options?: Options<GetWeatherForecastsData>) => createQueryKey('getWeatherForecasts', options);

export const getWeatherForecastsOptions = (options?: Options<GetWeatherForecastsData>) => queryOptions<GetWeatherForecastsResponse, GetWeatherForecastsError, GetWeatherForecastsResponse, ReturnType<typeof getWeatherForecastsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWeatherForecasts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWeatherForecastsQueryKey(options)
});

export const createWeatherForecastMutation = (options?: Partial<Options<CreateWeatherForecastData>>): UseMutationOptions<CreateWeatherForecastResponse, CreateWeatherForecastError, Options<CreateWeatherForecastData>> => {
    const mutationOptions: UseMutationOptions<CreateWeatherForecastResponse, CreateWeatherForecastError, Options<CreateWeatherForecastData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createWeatherForecast({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const removeWeatherForecastMutation = (options?: Partial<Options<RemoveWeatherForecastData>>): UseMutationOptions<RemoveWeatherForecastResponse, RemoveWeatherForecastError, Options<RemoveWeatherForecastData>> => {
    const mutationOptions: UseMutationOptions<RemoveWeatherForecastResponse, RemoveWeatherForecastError, Options<RemoveWeatherForecastData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeWeatherForecast({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getWeatherForecastQueryKey = (options: Options<GetWeatherForecastData>) => createQueryKey('getWeatherForecast', options);

export const getWeatherForecastOptions = (options: Options<GetWeatherForecastData>) => queryOptions<GetWeatherForecastResponse, GetWeatherForecastError, GetWeatherForecastResponse, ReturnType<typeof getWeatherForecastQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getWeatherForecast({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getWeatherForecastQueryKey(options)
});

export const updateWeatherForecastMutation = (options?: Partial<Options<UpdateWeatherForecastData>>): UseMutationOptions<UpdateWeatherForecastResponse, UpdateWeatherForecastError, Options<UpdateWeatherForecastData>> => {
    const mutationOptions: UseMutationOptions<UpdateWeatherForecastResponse, UpdateWeatherForecastError, Options<UpdateWeatherForecastData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateWeatherForecast({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const removeWeatherForecastsMutation = (options?: Partial<Options<RemoveWeatherForecastsData>>): UseMutationOptions<RemoveWeatherForecastsResponse, RemoveWeatherForecastsError, Options<RemoveWeatherForecastsData>> => {
    const mutationOptions: UseMutationOptions<RemoveWeatherForecastsResponse, RemoveWeatherForecastsError, Options<RemoveWeatherForecastsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeWeatherForecasts({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options);

export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, DefaultError, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserQueryKey(options)
});

export const getUsersQueryKey = (options?: Options<GetUsersData>) => createQueryKey('getUsers', options);

export const getUsersOptions = (options?: Options<GetUsersData>) => queryOptions<GetUsersResponse, DefaultError, GetUsersResponse, ReturnType<typeof getUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersQueryKey(options)
});

export const removeUserMutation = (options?: Partial<Options<RemoveUserData>>): UseMutationOptions<RemoveUserResponse, RemoveUserError, Options<RemoveUserData>> => {
    const mutationOptions: UseMutationOptions<RemoveUserResponse, RemoveUserError, Options<RemoveUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const removeUsersMutation = (options?: Partial<Options<RemoveUsersData>>): UseMutationOptions<RemoveUsersResponse, DefaultError, Options<RemoveUsersData>> => {
    const mutationOptions: UseMutationOptions<RemoveUsersResponse, DefaultError, Options<RemoveUsersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeUsers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<unknown, RegisterError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<unknown, RegisterError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<unknown, LogoutError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, LogoutError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const confirmEmailQueryKey = (options?: Options<ConfirmEmailData>) => createQueryKey('confirmEmail', options);

export const confirmEmailOptions = (options?: Options<ConfirmEmailData>) => queryOptions<unknown, ConfirmEmailError, unknown, ReturnType<typeof confirmEmailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await confirmEmail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: confirmEmailQueryKey(options)
});

export const resendConfirmationEmailMutation = (options?: Partial<Options<ResendConfirmationEmailData>>): UseMutationOptions<unknown, ResendConfirmationEmailError, Options<ResendConfirmationEmailData>> => {
    const mutationOptions: UseMutationOptions<unknown, ResendConfirmationEmailError, Options<ResendConfirmationEmailData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await resendConfirmationEmail({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const forgotPasswordMutation = (options?: Partial<Options<ForgotPasswordData>>): UseMutationOptions<unknown, ForgotPasswordError, Options<ForgotPasswordData>> => {
    const mutationOptions: UseMutationOptions<unknown, ForgotPasswordError, Options<ForgotPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await forgotPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const resetPasswordMutation = (options?: Partial<Options<ResetPasswordData>>): UseMutationOptions<unknown, ResetPasswordError, Options<ResetPasswordData>> => {
    const mutationOptions: UseMutationOptions<unknown, ResetPasswordError, Options<ResetPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await resetPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateInfoMutation = (options?: Partial<Options<UpdateInfoData>>): UseMutationOptions<UpdateInfoResponse, UpdateInfoError, Options<UpdateInfoData>> => {
    const mutationOptions: UseMutationOptions<UpdateInfoResponse, UpdateInfoError, Options<UpdateInfoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateInfo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
